---
- name: "Tests"
  hosts: prod
  tasks:
    - name: Test availability slave
      uri:
        url: http://{{ ansible_host }}
        method: GET
        return_content: yes
      register: this
      failed_when: "'Hello world!' not in this.content"
...
